# SPDX-FileCopyrightText: 2026 Alexandr Savca
# SPDX-License-Identifier: GPL-3.0-or-later

documentation_dir = get_option('datadir') / 'doc' / meson.project_name()

install_data(
  '../README.md',
  '../HISTORY.md',
  '../CONTRIBUTING.md',
  '../MAINTAINING.md',
  'architecture.md',
  'integration.md',
  'testing.md',
  'abi.md',
  'code-style.md',
  install_dir: documentation_dir,
  install_tag: 'docs',
)
